env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

builds:
  -
    main: ./cmd/qbt/main.go
    binary: qbt
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - 386
      - amd64

release:
  prerelease: auto