// Command gen-docs generates Starlight-compatible markdown reference pages for
// every qbt command using spf13/cobra's doc package.
//
// It is wired into `make docs` and verified in CI, so the committed docs under
// docs/src/content/docs/commands always match the real command tree.
//
// Usage:
//
//	go run ./tools/gen-docs [-out DIR]
package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/ludviglundgren/qbittorrent-cli/cmd"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

const defaultOutDir = "docs/src/content/docs/commands"

func main() {
	log.SetFlags(0)

	outDir := defaultOutDir
	if len(os.Args) > 2 && os.Args[1] == "-out" {
		outDir = os.Args[2]
	}

	if err := run(outDir); err != nil {
		log.Fatalf("gen-docs: %v", err)
	}

	log.Printf("gen-docs: wrote command reference to %s", outDir)
}

func run(outDir string) error {
	rootCmd := cmd.NewRootCmd("dev", "none", "unknown")

	// Replace the auto-generated help command with a hidden one so it does not
	// show up as a "SEE ALSO" link to a page we never generate.
	rootCmd.SetHelpCommand(&cobra.Command{
		Use:    "no-help",
		Hidden: true,
		Run:    func(*cobra.Command, []string) {},
	})

	// Disable the "Auto generated by spf13/cobra on <date>" footer on every
	// command. The date would otherwise change on every run and break the CI
	// staleness check.
	disableAutoGenTag(rootCmd)

	// Map each generated filename to the command's short description so the
	// filePrepender (which only receives the filename) can emit it as
	// frontmatter.
	descriptions := map[string]string{}
	collectDescriptions(rootCmd, descriptions)

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	// Remove previously generated pages so renamed or removed commands do not
	// leave orphaned files behind.
	stale, err := filepath.Glob(filepath.Join(outDir, "*.md"))
	if err != nil {
		return fmt.Errorf("list stale docs: %w", err)
	}
	for _, f := range stale {
		if err := os.Remove(f); err != nil {
			return fmt.Errorf("remove stale doc %s: %w", f, err)
		}
	}

	filePrepender := func(filename string) string {
		base := filepath.Base(filename)
		name := strings.TrimSuffix(base, filepath.Ext(base)) // qbt_torrent_add
		title := strings.ReplaceAll(name, "_", " ")          // qbt torrent add

		var b strings.Builder
		b.WriteString("---\n")
		b.WriteString("title: " + yamlString(title) + "\n")
		if desc := descriptions[base]; desc != "" {
			b.WriteString("description: " + yamlString(desc) + "\n")
		}
		// These pages are generated; hide the "Edit this page" link.
		b.WriteString("editUrl: false\n")
		b.WriteString("---\n\n")
		return b.String()
	}

	// cobra emits cross-links as "qbt_torrent_add.md". Every page lives in the
	// same directory and is served by Starlight at ".../commands/<slug>/", so a
	// sibling page is one level up: "../qbt_torrent_add/".
	linkHandler := func(name string) string {
		return "../" + strings.TrimSuffix(name, ".md") + "/"
	}

	if err := doc.GenMarkdownTreeCustom(rootCmd, outDir, filePrepender, linkHandler); err != nil {
		return err
	}

	// Drop cobra's leading "## <command path>" heading from each page; Starlight
	// already renders the frontmatter title as the page heading, so it would be a
	// duplicate. The short description line below it is kept as the lead.
	generated, err := filepath.Glob(filepath.Join(outDir, "*.md"))
	if err != nil {
		return fmt.Errorf("list generated docs: %w", err)
	}
	for _, f := range generated {
		if err := stripCommandHeading(f); err != nil {
			return fmt.Errorf("post-process %s: %w", f, err)
		}
	}

	return nil
}

// stripCommandHeading removes the redundant "## <command path>" heading that
// cobra writes at the top of the page body, leaving the frontmatter and the
// rest of the content (including the short description lead) intact.
func stripCommandHeading(path string) error {
	raw, err := os.ReadFile(path)
	if err != nil {
		return err
	}

	content := string(raw)

	const fence = "---\n"
	if !strings.HasPrefix(content, fence) {
		return nil
	}
	rel := strings.Index(content[len(fence):], "\n"+fence)
	if rel == -1 {
		return nil
	}
	headerEnd := len(fence) + rel + len("\n"+fence)

	header := content[:headerEnd]
	body := strings.TrimLeft(content[headerEnd:], "\n")

	if strings.HasPrefix(body, "## ") {
		if nl := strings.IndexByte(body, '\n'); nl != -1 {
			body = strings.TrimLeft(body[nl+1:], "\n")
		}
	}

	return os.WriteFile(path, []byte(header+"\n"+body), 0o644)
}

// disableAutoGenTag turns off the cobra auto-gen footer for cmd and all of its
// descendants.
func disableAutoGenTag(cmd *cobra.Command) {
	cmd.DisableAutoGenTag = true
	for _, c := range cmd.Commands() {
		disableAutoGenTag(c)
	}
}

// collectDescriptions walks the command tree and records each command's short
// description keyed by the markdown filename cobra will generate for it.
func collectDescriptions(cmd *cobra.Command, out map[string]string) {
	base := strings.ReplaceAll(cmd.CommandPath(), " ", "_") + ".md"
	out[base] = cmd.Short
	for _, c := range cmd.Commands() {
		collectDescriptions(c, out)
	}
}

// yamlString quotes a value for safe use in YAML frontmatter.
func yamlString(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return `"` + s + `"`
}
