name: test

on:
  push:
    branches:
      - "master"
      - "develop"
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.3'
          cache: true

      - name: Test
        run: go test -v ./...
